
USE [LootManagementDB]
GO
SET IDENTITY_INSERT [dbo].[Gears] ON 

INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (1, N'No Equipment', 0, 0, 0, 0, 0, N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (2, N'Normal raid', 710, 2, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (3, N'Normal raid', 710, 2, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (4, N'Normal raid', 710, 2, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (5, N'Normal raid', 710, 2, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (6, N'Normal raid', 710, 2, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (7, N'Normal raid', 710, 2, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (8, N'Normal raid', 710, 2, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (9, N'Normal raid', 710, 2, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (10, N'Normal raid', 710, 3, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (11, N'Normal raid', 710, 3, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (12, N'Normal raid', 710, 3, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (13, N'Normal raid', 710, 3, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (14, N'Normal raid', 710, 3, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (15, N'Normal raid', 710, 3, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (16, N'Normal raid', 710, 3, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (17, N'Normal raid', 710, 3, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (18, N'Normal raid', 710, 4, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (19, N'Normal raid', 710, 4, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (20, N'Normal raid', 710, 4, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (21, N'Normal raid', 710, 4, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (22, N'Normal raid', 710, 4, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (23, N'Normal raid', 710, 4, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (24, N'Normal raid', 710, 4, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (25, N'Normal raid', 710, 4, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (26, N'Normal raid', 710, 5, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (27, N'Normal raid', 710, 5, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (28, N'Normal raid', 710, 5, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (29, N'Normal raid', 710, 5, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (30, N'Normal raid', 710, 5, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (31, N'Normal raid', 710, 5, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (32, N'Normal raid', 710, 5, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (33, N'Normal raid', 710, 5, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (34, N'Normal raid', 710, 6, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (35, N'Normal raid', 710, 6, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (36, N'Normal raid', 710, 6, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (37, N'Normal raid', 710, 6, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (38, N'Normal raid', 710, 6, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (39, N'Normal raid', 710, 6, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (40, N'Normal raid', 710, 6, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (41, N'Normal raid', 710, 6, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (42, N'Normal raid', 710, 7, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (43, N'Normal raid', 710, 7, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (44, N'Normal raid', 710, 7, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (45, N'Normal raid', 710, 7, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (46, N'Normal raid', 710, 7, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (47, N'Normal raid', 710, 7, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (48, N'Normal raid', 710, 7, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (49, N'Normal raid', 710, 7, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (50, N'Normal raid', 710, 8, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (51, N'Normal raid', 710, 8, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (52, N'Normal raid', 710, 8, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (53, N'Normal raid', 710, 8, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (54, N'Normal raid', 710, 8, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (55, N'Normal raid', 710, 8, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (56, N'Normal raid', 710, 8, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (57, N'Normal raid', 710, 8, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (58, N'Normal raid', 710, 9, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (59, N'Normal raid', 710, 9, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (60, N'Normal raid', 710, 9, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (61, N'Normal raid', 710, 9, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (62, N'Normal raid', 710, 9, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (63, N'Normal raid', 710, 9, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (64, N'Normal raid', 710, 9, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (65, N'Normal raid', 710, 9, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (66, N'Normal raid', 710, 10, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (67, N'Normal raid', 710, 10, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (68, N'Normal raid', 710, 10, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (69, N'Normal raid', 710, 10, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (70, N'Normal raid', 710, 10, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (71, N'Normal raid', 710, 10, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (72, N'Normal raid', 710, 10, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (73, N'Normal raid', 710, 10, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (74, N'Normal raid', 710, 11, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (75, N'Normal raid', 710, 11, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (76, N'Normal raid', 710, 11, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (77, N'Normal raid', 710, 11, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (78, N'Normal raid', 710, 11, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (79, N'Normal raid', 710, 11, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (80, N'Normal raid', 710, 11, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (81, N'Normal raid', 710, 11, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (82, N'Normal raid', 710, 1, 1, 9, N'1', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (83, N'Normal raid', 710, 1, 1, 9, N'2', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (84, N'Normal raid', 710, 1, 1, 9, N'3', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (85, N'Normal raid', 710, 1, 1, 9, N'4', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (86, N'Normal raid', 710, 1, 1, 9, N'5', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (87, N'Normal raid', 710, 1, 1, 9, N'6', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (88, N'Normal raid', 710, 1, 1, 9, N'7', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (89, N'Normal raid', 710, 1, 1, 9, N'8', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (90, N'Normal raid', 710, 1, 1, 9, N'9', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (91, N'Normal raid', 710, 1, 1, 9, N'10', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (92, N'Normal raid', 710, 1, 1, 9, N'11', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (93, N'Normal raid', 710, 1, 1, 9, N'12', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (94, N'Normal raid', 710, 1, 1, 9, N'13', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (95, N'Normal raid', 710, 1, 1, 9, N'14', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (96, N'Normal raid', 710, 1, 1, 9, N'15', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (97, N'Normal raid', 710, 1, 1, 9, N'16', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (98, N'Normal raid', 710, 1, 1, 9, N'17', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (99, N'Normal raid', 710, 1, 1, 9, N'18', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (100, N'Normal raid', 710, 1, 1, 9, N'19', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (101, N'Normal raid', 710, 1, 1, 9, N'20', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (102, N'Normal raid', 710, 1, 1, 9, N'21', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (103, N'Crafted', 710, 2, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (104, N'Crafted', 710, 2, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (105, N'Crafted', 710, 2, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (106, N'Crafted', 710, 2, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (107, N'Crafted', 710, 2, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (108, N'Crafted', 710, 2, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (109, N'Crafted', 710, 2, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (110, N'Crafted', 710, 2, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (111, N'Crafted', 710, 3, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (112, N'Crafted', 710, 3, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (113, N'Crafted', 710, 3, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (114, N'Crafted', 710, 3, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (115, N'Crafted', 710, 3, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (116, N'Crafted', 710, 3, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (117, N'Crafted', 710, 3, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (118, N'Crafted', 710, 3, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (119, N'Crafted', 710, 4, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (120, N'Crafted', 710, 4, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (121, N'Crafted', 710, 4, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (122, N'Crafted', 710, 4, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (123, N'Crafted', 710, 4, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (124, N'Crafted', 710, 4, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (125, N'Crafted', 710, 4, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (126, N'Crafted', 710, 4, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (127, N'Crafted', 710, 5, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (128, N'Crafted', 710, 5, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (129, N'Crafted', 710, 5, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (130, N'Crafted', 710, 5, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (131, N'Crafted', 710, 5, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (132, N'Crafted', 710, 5, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (133, N'Crafted', 710, 5, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (134, N'Crafted', 710, 5, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (135, N'Crafted', 710, 6, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (136, N'Crafted', 710, 6, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (137, N'Crafted', 710, 6, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (138, N'Crafted', 710, 6, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (139, N'Crafted', 710, 6, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (140, N'Crafted', 710, 6, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (141, N'Crafted', 710, 6, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (142, N'Crafted', 710, 6, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (143, N'Crafted', 710, 7, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (144, N'Crafted', 710, 7, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (145, N'Crafted', 710, 7, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (146, N'Crafted', 710, 7, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (147, N'Crafted', 710, 7, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (148, N'Crafted', 710, 7, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (149, N'Crafted', 710, 7, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (150, N'Crafted', 710, 7, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (151, N'Crafted', 710, 8, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (152, N'Crafted', 710, 8, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (153, N'Crafted', 710, 8, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (154, N'Crafted', 710, 8, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (155, N'Crafted', 710, 8, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (156, N'Crafted', 710, 8, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (157, N'Crafted', 710, 8, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (158, N'Crafted', 710, 8, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (159, N'Crafted', 710, 9, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (160, N'Crafted', 710, 9, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (161, N'Crafted', 710, 9, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (162, N'Crafted', 710, 9, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (163, N'Crafted', 710, 9, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (164, N'Crafted', 710, 9, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (165, N'Crafted', 710, 9, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (166, N'Crafted', 710, 9, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (167, N'Crafted', 710, 10, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (168, N'Crafted', 710, 10, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (169, N'Crafted', 710, 10, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (170, N'Crafted', 710, 10, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (171, N'Crafted', 710, 10, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (172, N'Crafted', 710, 10, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (173, N'Crafted', 710, 10, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (174, N'Crafted', 710, 10, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (175, N'Crafted', 710, 11, 1, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (176, N'Crafted', 710, 11, 1, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (177, N'Crafted', 710, 11, 1, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (178, N'Crafted', 710, 11, 1, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (179, N'Crafted', 710, 11, 1, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (180, N'Crafted', 710, 11, 1, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (181, N'Crafted', 710, 11, 1, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (182, N'Crafted', 710, 11, 1, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (183, N'Crafted', 710, 1, 1, 9, N'1', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (184, N'Crafted', 710, 1, 1, 9, N'2', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (185, N'Crafted', 710, 1, 1, 9, N'3', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (186, N'Crafted', 710, 1, 1, 9, N'4', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (187, N'Crafted', 710, 1, 1, 9, N'5', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (188, N'Crafted', 710, 1, 1, 9, N'6', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (189, N'Crafted', 710, 1, 1, 9, N'7', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (190, N'Crafted', 710, 1, 1, 9, N'8', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (191, N'Crafted', 710, 1, 1, 9, N'9', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (192, N'Crafted', 710, 1, 1, 9, N'10', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (193, N'Crafted', 710, 1, 1, 9, N'11', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (194, N'Crafted', 710, 1, 1, 9, N'12', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (195, N'Crafted', 710, 1, 1, 9, N'13', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (196, N'Crafted', 710, 1, 1, 9, N'14', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (197, N'Crafted', 710, 1, 1, 9, N'15', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (198, N'Crafted', 710, 1, 1, 9, N'16', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (199, N'Crafted', 710, 1, 1, 9, N'17', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (200, N'Crafted', 710, 1, 1, 9, N'18', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (201, N'Crafted', 710, 1, 1, 9, N'19', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (202, N'Crafted', 710, 1, 1, 9, N'20', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (203, N'Crafted', 710, 1, 1, 9, N'21', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (204, N'Tome gear', 720, 2, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (205, N'Tome gear', 720, 2, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (206, N'Tome gear', 720, 2, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (207, N'Tome gear', 720, 2, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (208, N'Tome gear', 720, 2, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (209, N'Tome gear', 720, 2, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (210, N'Tome gear', 720, 2, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (211, N'Tome gear', 720, 2, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (212, N'Tome gear', 720, 3, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (213, N'Tome gear', 720, 3, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (214, N'Tome gear', 720, 3, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (215, N'Tome gear', 720, 3, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (216, N'Tome gear', 720, 3, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (217, N'Tome gear', 720, 3, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (218, N'Tome gear', 720, 3, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (219, N'Tome gear', 720, 3, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (220, N'Tome gear', 720, 4, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (221, N'Tome gear', 720, 4, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (222, N'Tome gear', 720, 4, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (223, N'Tome gear', 720, 4, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (224, N'Tome gear', 720, 4, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (225, N'Tome gear', 720, 4, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (226, N'Tome gear', 720, 4, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (227, N'Tome gear', 720, 4, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (228, N'Tome gear', 720, 5, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (229, N'Tome gear', 720, 5, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (230, N'Tome gear', 720, 5, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (231, N'Tome gear', 720, 5, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (232, N'Tome gear', 720, 5, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (233, N'Tome gear', 720, 5, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (234, N'Tome gear', 720, 5, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (235, N'Tome gear', 720, 5, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (236, N'Tome gear', 720, 6, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (237, N'Tome gear', 720, 6, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (238, N'Tome gear', 720, 6, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (239, N'Tome gear', 720, 6, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (240, N'Tome gear', 720, 6, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (241, N'Tome gear', 720, 6, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (242, N'Tome gear', 720, 6, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (243, N'Tome gear', 720, 6, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (244, N'Tome gear', 720, 7, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (245, N'Tome gear', 720, 7, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (246, N'Tome gear', 720, 7, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (247, N'Tome gear', 720, 7, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (248, N'Tome gear', 720, 7, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (249, N'Tome gear', 720, 7, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (250, N'Tome gear', 720, 7, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (251, N'Tome gear', 720, 7, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (252, N'Tome gear', 720, 8, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (253, N'Tome gear', 720, 8, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (254, N'Tome gear', 720, 8, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (255, N'Tome gear', 720, 8, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (256, N'Tome gear', 720, 8, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (257, N'Tome gear', 720, 8, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (258, N'Tome gear', 720, 8, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (259, N'Tome gear', 720, 8, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (260, N'Tome gear', 720, 9, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (261, N'Tome gear', 720, 9, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (262, N'Tome gear', 720, 9, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (263, N'Tome gear', 720, 9, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (264, N'Tome gear', 720, 9, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (265, N'Tome gear', 720, 9, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (266, N'Tome gear', 720, 9, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (267, N'Tome gear', 720, 9, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (268, N'Tome gear', 720, 10, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (269, N'Tome gear', 720, 10, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (270, N'Tome gear', 720, 10, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (271, N'Tome gear', 720, 10, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (272, N'Tome gear', 720, 10, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (273, N'Tome gear', 720, 10, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (274, N'Tome gear', 720, 10, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (275, N'Tome gear', 720, 10, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (276, N'Tome gear', 720, 11, 2, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (277, N'Tome gear', 720, 11, 2, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (278, N'Tome gear', 720, 11, 2, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (279, N'Tome gear', 720, 11, 2, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (280, N'Tome gear', 720, 11, 2, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (281, N'Tome gear', 720, 11, 2, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (282, N'Tome gear', 720, 11, 2, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (283, N'Tome gear', 720, 11, 2, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (284, N'Tome gear', 720, 1, 2, 9, N'1', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (285, N'Tome gear', 720, 1, 2, 9, N'2', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (286, N'Tome gear', 720, 1, 2, 9, N'3', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (287, N'Tome gear', 720, 1, 2, 9, N'4', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (288, N'Tome gear', 720, 1, 2, 9, N'5', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (289, N'Tome gear', 720, 1, 2, 9, N'6', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (290, N'Tome gear', 720, 1, 2, 9, N'7', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (291, N'Tome gear', 720, 1, 2, 9, N'8', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (292, N'Tome gear', 720, 1, 2, 9, N'9', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (293, N'Tome gear', 720, 1, 2, 9, N'10', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (294, N'Tome gear', 720, 1, 2, 9, N'11', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (295, N'Tome gear', 720, 1, 2, 9, N'12', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (296, N'Tome gear', 720, 1, 2, 9, N'13', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (297, N'Tome gear', 720, 1, 2, 9, N'14', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (298, N'Tome gear', 720, 1, 2, 9, N'15', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (299, N'Tome gear', 720, 1, 2, 9, N'16', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (300, N'Tome gear', 720, 1, 2, 9, N'17', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (301, N'Tome gear', 720, 1, 2, 9, N'18', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (302, N'Tome gear', 720, 1, 2, 9, N'19', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (303, N'Tome gear', 720, 1, 2, 9, N'20', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (304, N'Tome gear', 720, 1, 2, 9, N'21', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (305, N'Augmented tome', 730, 2, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (306, N'Augmented tome', 730, 2, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (307, N'Augmented tome', 730, 2, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (308, N'Augmented tome', 730, 2, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (309, N'Augmented tome', 730, 2, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (310, N'Augmented tome', 730, 2, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (311, N'Augmented tome', 730, 2, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (312, N'Augmented tome', 730, 2, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (313, N'Augmented tome', 730, 3, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (314, N'Augmented tome', 730, 3, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (315, N'Augmented tome', 730, 3, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (316, N'Augmented tome', 730, 3, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (317, N'Augmented tome', 730, 3, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (318, N'Augmented tome', 730, 3, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (319, N'Augmented tome', 730, 3, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (320, N'Augmented tome', 730, 3, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (321, N'Augmented tome', 730, 4, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (322, N'Augmented tome', 730, 4, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (323, N'Augmented tome', 730, 4, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (324, N'Augmented tome', 730, 4, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (325, N'Augmented tome', 730, 4, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (326, N'Augmented tome', 730, 4, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (327, N'Augmented tome', 730, 4, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (328, N'Augmented tome', 730, 4, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (329, N'Augmented tome', 730, 5, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (330, N'Augmented tome', 730, 5, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (331, N'Augmented tome', 730, 5, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (332, N'Augmented tome', 730, 5, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (333, N'Augmented tome', 730, 5, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (334, N'Augmented tome', 730, 5, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (335, N'Augmented tome', 730, 5, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (336, N'Augmented tome', 730, 5, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (337, N'Augmented tome', 730, 6, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (338, N'Augmented tome', 730, 6, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (339, N'Augmented tome', 730, 6, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (340, N'Augmented tome', 730, 6, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (341, N'Augmented tome', 730, 6, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (342, N'Augmented tome', 730, 6, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (343, N'Augmented tome', 730, 6, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (344, N'Augmented tome', 730, 6, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (345, N'Augmented tome', 730, 7, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (346, N'Augmented tome', 730, 7, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (347, N'Augmented tome', 730, 7, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (348, N'Augmented tome', 730, 7, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (349, N'Augmented tome', 730, 7, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (350, N'Augmented tome', 730, 7, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (351, N'Augmented tome', 730, 7, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (352, N'Augmented tome', 730, 7, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (353, N'Augmented tome', 730, 8, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (354, N'Augmented tome', 730, 8, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (355, N'Augmented tome', 730, 8, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (356, N'Augmented tome', 730, 8, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (357, N'Augmented tome', 730, 8, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (358, N'Augmented tome', 730, 8, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (359, N'Augmented tome', 730, 8, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (360, N'Augmented tome', 730, 8, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (361, N'Augmented tome', 730, 9, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (362, N'Augmented tome', 730, 9, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (363, N'Augmented tome', 730, 9, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (364, N'Augmented tome', 730, 9, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (365, N'Augmented tome', 730, 9, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (366, N'Augmented tome', 730, 9, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (367, N'Augmented tome', 730, 9, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (368, N'Augmented tome', 730, 9, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (369, N'Augmented tome', 730, 10, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (370, N'Augmented tome', 730, 10, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (371, N'Augmented tome', 730, 10, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (372, N'Augmented tome', 730, 10, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (373, N'Augmented tome', 730, 10, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (374, N'Augmented tome', 730, 10, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (375, N'Augmented tome', 730, 10, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (376, N'Augmented tome', 730, 10, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (377, N'Augmented tome', 730, 11, 3, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (378, N'Augmented tome', 730, 11, 3, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (379, N'Augmented tome', 730, 11, 3, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (380, N'Augmented tome', 730, 11, 3, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (381, N'Augmented tome', 730, 11, 3, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (382, N'Augmented tome', 730, 11, 3, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (383, N'Augmented tome', 730, 11, 3, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (384, N'Augmented tome', 730, 11, 3, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (385, N'Augmented tome', 730, 1, 3, 9, N'1', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (386, N'Augmented tome', 730, 1, 3, 9, N'2', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (387, N'Augmented tome', 730, 1, 3, 9, N'3', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (388, N'Augmented tome', 730, 1, 3, 9, N'4', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (389, N'Augmented tome', 730, 1, 3, 9, N'5', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (390, N'Augmented tome', 730, 1, 3, 9, N'6', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (391, N'Augmented tome', 730, 1, 3, 9, N'7', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (392, N'Augmented tome', 730, 1, 3, 9, N'8', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (393, N'Augmented tome', 730, 1, 3, 9, N'9', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (394, N'Augmented tome', 730, 1, 3, 9, N'10', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (395, N'Augmented tome', 730, 1, 3, 9, N'11', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (396, N'Augmented tome', 730, 1, 3, 9, N'12', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (397, N'Augmented tome', 730, 1, 3, 9, N'13', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (398, N'Augmented tome', 730, 1, 3, 9, N'14', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (399, N'Augmented tome', 730, 1, 3, 9, N'15', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (400, N'Augmented tome', 730, 1, 3, 9, N'16', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (401, N'Augmented tome', 730, 1, 3, 9, N'17', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (402, N'Augmented tome', 730, 1, 3, 9, N'18', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (403, N'Augmented tome', 730, 1, 3, 9, N'19', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (404, N'Augmented tome', 730, 1, 3, 9, N'20', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (405, N'Augmented tome', 730, 1, 3, 9, N'21', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (406, N'Raid', 730, 2, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (407, N'Raid', 730, 2, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (408, N'Raid', 730, 2, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (409, N'Raid', 730, 2, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (410, N'Raid', 730, 2, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (411, N'Raid', 730, 2, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (412, N'Raid', 730, 2, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (413, N'Raid', 730, 2, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (414, N'Raid', 730, 3, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (415, N'Raid', 730, 3, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (416, N'Raid', 730, 3, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (417, N'Raid', 730, 3, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (418, N'Raid', 730, 3, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (419, N'Raid', 730, 3, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (420, N'Raid', 730, 3, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (421, N'Raid', 730, 3, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (422, N'Raid', 730, 4, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (423, N'Raid', 730, 4, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (424, N'Raid', 730, 4, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (425, N'Raid', 730, 4, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (426, N'Raid', 730, 4, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (427, N'Raid', 730, 4, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (428, N'Raid', 730, 4, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (429, N'Raid', 730, 4, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (430, N'Raid', 730, 5, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (431, N'Raid', 730, 5, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (432, N'Raid', 730, 5, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (433, N'Raid', 730, 5, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (434, N'Raid', 730, 5, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (435, N'Raid', 730, 5, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (436, N'Raid', 730, 5, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (437, N'Raid', 730, 5, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (438, N'Raid', 730, 6, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (439, N'Raid', 730, 6, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (440, N'Raid', 730, 6, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (441, N'Raid', 730, 6, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (442, N'Raid', 730, 6, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (443, N'Raid', 730, 6, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (444, N'Raid', 730, 6, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (445, N'Raid', 730, 6, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (446, N'Raid', 730, 7, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (447, N'Raid', 730, 7, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (448, N'Raid', 730, 7, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (449, N'Raid', 730, 7, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (450, N'Raid', 730, 7, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (451, N'Raid', 730, 7, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (452, N'Raid', 730, 7, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (453, N'Raid', 730, 7, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (454, N'Raid', 730, 8, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (455, N'Raid', 730, 8, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (456, N'Raid', 730, 8, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (457, N'Raid', 730, 8, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (458, N'Raid', 730, 8, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (459, N'Raid', 730, 8, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (460, N'Raid', 730, 8, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (461, N'Raid', 730, 8, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (462, N'Raid', 730, 9, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (463, N'Raid', 730, 9, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (464, N'Raid', 730, 9, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (465, N'Raid', 730, 9, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (466, N'Raid', 730, 9, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (467, N'Raid', 730, 9, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (468, N'Raid', 730, 9, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (469, N'Raid', 730, 9, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (470, N'Raid', 730, 10, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (471, N'Raid', 730, 10, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (472, N'Raid', 730, 10, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (473, N'Raid', 730, 10, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (474, N'Raid', 730, 10, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (475, N'Raid', 730, 10, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (476, N'Raid', 730, 10, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (477, N'Raid', 730, 10, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (478, N'Raid', 730, 11, 4, 1, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (479, N'Raid', 730, 11, 4, 2, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (480, N'Raid', 730, 11, 4, 3, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (481, N'Raid', 730, 11, 4, 4, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (482, N'Raid', 730, 11, 4, 5, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (483, N'Raid', 730, 11, 4, 6, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (484, N'Raid', 730, 11, 4, 7, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (485, N'Raid', 730, 11, 4, 8, N'0', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (486, N'Raid', 730, 1, 4, 9, N'1', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (487, N'Raid', 730, 1, 4, 9, N'2', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (488, N'Raid', 730, 1, 4, 9, N'3', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (489, N'Raid', 730, 1, 4, 9, N'4', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (490, N'Raid', 730, 1, 4, 9, N'5', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (491, N'Raid', 730, 1, 4, 9, N'6', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (492, N'Raid', 730, 1, 4, 9, N'7', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (493, N'Raid', 730, 1, 4, 9, N'8', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (494, N'Raid', 730, 1, 4, 9, N'9', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (495, N'Raid', 730, 1, 4, 9, N'10', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (496, N'Raid', 730, 1, 4, 9, N'11', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (497, N'Raid', 730, 1, 4, 9, N'12', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (498, N'Raid', 730, 1, 4, 9, N'13', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (499, N'Raid', 730, 1, 4, 9, N'14', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (500, N'Raid', 730, 1, 4, 9, N'15', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (501, N'Raid', 730, 1, 4, 9, N'16', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (502, N'Raid', 730, 1, 4, 9, N'17', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (503, N'Raid', 730, 1, 4, 9, N'18', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (504, N'Raid', 730, 1, 4, 9, N'19', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (505, N'Raid', 730, 1, 4, 9, N'20', N'0', 0)
INSERT [dbo].[Gears] ([Id], [Name], [GearLevel], [GearType], [GearStage], [GearCategory], [GearWeaponCategory], [IconPath], [EtroGearId]) VALUES (506, N'Raid', 730, 1, 4, 9, N'21', N'0', 0)
